
package javaapplication16.Frame;
import java.awt.Color;
import java.awt.Cursor;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPWelcome = new javax.swing.JPanel();
        LabelWelcome = new javax.swing.JLabel();
        JPLogin = new javax.swing.JPanel();
        LabelPassword = new javax.swing.JLabel();
        LabelUsername = new javax.swing.JLabel();
        IconUser = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LineUsername = new javax.swing.JSeparator();
        LinePassword = new javax.swing.JSeparator();
        ButtonEnter = new javax.swing.JButton();
        IconPassword = new javax.swing.JLabel();
        IconUsername = new javax.swing.JLabel();
        ButtonSignUp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JPSignUp = new javax.swing.JPanel();
        LabelSignUp = new javax.swing.JLabel();
        LabelUsername1 = new javax.swing.JLabel();
        LabelPassword1 = new javax.swing.JLabel();
        ButtonRollback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonMinimize = new javax.swing.JButton();
        ButtonClose = new javax.swing.JButton();
        JPAdminMenu = new javax.swing.JPanel();
        ButtonStatistics = new javax.swing.JButton();
        ButtonReports = new javax.swing.JButton();
        ButtonLogOut1 = new javax.swing.JButton();
        ButtonQuery1 = new javax.swing.JButton();
        ButtonConfiguration1 = new javax.swing.JButton();
        JPUserMenu = new javax.swing.JPanel();
        ButtonQuery = new javax.swing.JButton();
        ButtonConfiguration = new javax.swing.JButton();
        ButtonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPWelcome.setBackground(new java.awt.Color(255, 255, 255));
        JPWelcome.setForeground(new java.awt.Color(255, 255, 255));
        JPWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPWelcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPWelcomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPWelcomeMouseExited(evt);
            }
        });
        JPWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        LabelWelcome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        LabelWelcome.setForeground(new java.awt.Color(29, 41, 81));
        LabelWelcome.setText("Welcome");
        JPWelcome.add(LabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 220, 70));

        getContentPane().add(JPWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        JPLogin.setBackground(new java.awt.Color(29, 41, 81));
        JPLogin.setForeground(new java.awt.Color(255, 255, 255));
        JPLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        LabelPassword.setText("Password:");
        JPLogin.add(LabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 90, 20));

        LabelUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsername.setText("Username:");
        JPLogin.add(LabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 20));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Archive.png"))); // NOI18N
        JPLogin.add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, 150));

        UsernameField.setBackground(new java.awt.Color(29, 41, 81));
        UsernameField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(240, 240, 240));
        UsernameField.setBorder(null);
        JPLogin.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 170, 20));

        PasswordField.setBackground(new java.awt.Color(29, 41, 81));
        PasswordField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setBorder(null);
        JPLogin.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 399, 170, 20));
        JPLogin.add(LineUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 210, 10));
        JPLogin.add(LinePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 210, 10));

        ButtonEnter.setBackground(new java.awt.Color(29, 41, 81));
        ButtonEnter.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ButtonEnter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEnter.setText("ENTER");
        ButtonEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ButtonEnter.setContentAreaFilled(false);
        ButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnterActionPerformed(evt);
            }
        });
        JPLogin.add(ButtonEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 100, 40));

        IconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Password.png"))); // NOI18N
        JPLogin.add(IconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 50, 30));

        IconUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/User.png"))); // NOI18N
        JPLogin.add(IconUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 30, 40));

        ButtonSignUp.setBackground(new java.awt.Color(29, 41, 81));
        ButtonSignUp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSignUp.setText("Sign Up");
        ButtonSignUp.setBorder(null);
        ButtonSignUp.setContentAreaFilled(false);
        ButtonSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSignUpMouseExited(evt);
            }
        });
        ButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignUpActionPerformed(evt);
            }
        });
        JPLogin.add(ButtonSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 80, -1));
        JPLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 513, 50, 20));

        getContentPane().add(JPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        JPSignUp.setBackground(new java.awt.Color(255, 255, 255));
        JPSignUp.setForeground(new java.awt.Color(255, 255, 255));
        JPSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        LabelSignUp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        LabelSignUp.setForeground(new java.awt.Color(29, 41, 81));
        LabelSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/AddUser.png"))); // NOI18N
        LabelSignUp.setText("Welcome");
        JPSignUp.add(LabelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 360, 140));

        LabelUsername1.setBackground(new java.awt.Color(255, 255, 255));
        LabelUsername1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelUsername1.setForeground(new java.awt.Color(29, 41, 81));
        LabelUsername1.setText("Password:");
        JPSignUp.add(LabelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 30));

        LabelPassword1.setBackground(new java.awt.Color(255, 255, 255));
        LabelPassword1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LabelPassword1.setForeground(new java.awt.Color(29, 41, 81));
        LabelPassword1.setText("Username:");
        JPSignUp.add(LabelPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        ButtonRollback.setBackground(new java.awt.Color(255, 255, 255));
        ButtonRollback.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRollback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Rollback.png"))); // NOI18N
        ButtonRollback.setBorder(null);
        ButtonRollback.setContentAreaFilled(false);
        ButtonRollback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonRollbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonRollbackMouseExited(evt);
            }
        });
        ButtonRollback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRollbackActionPerformed(evt);
            }
        });
        JPSignUp.add(ButtonRollback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        getContentPane().add(JPSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonMinimize.setBackground(new java.awt.Color(255, 255, 255));
        ButtonMinimize.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Minimize.png"))); // NOI18N
        ButtonMinimize.setContentAreaFilled(false);
        ButtonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMinimizeMouseExited(evt);
            }
        });
        ButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinimizeActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 40, 30));

        ButtonClose.setBackground(new java.awt.Color(255, 255, 255));
        ButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        ButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Close.png"))); // NOI18N
        ButtonClose.setContentAreaFilled(false);
        ButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCloseMouseExited(evt);
            }
        });
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        JPAdminMenu.setBackground(new java.awt.Color(255, 255, 255));
        JPAdminMenu.setForeground(new java.awt.Color(255, 255, 255));
        JPAdminMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonStatistics.setBackground(new java.awt.Color(255, 255, 255));
        ButtonStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Statistics.png"))); // NOI18N
        ButtonStatistics.setBorder(null);
        ButtonStatistics.setContentAreaFilled(false);
        ButtonStatistics.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonStatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonStatisticsMouseExited(evt);
            }
        });
        ButtonStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStatisticsActionPerformed(evt);
            }
        });
        JPAdminMenu.add(ButtonStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, 170));

        ButtonReports.setBackground(new java.awt.Color(255, 255, 255));
        ButtonReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Report.png"))); // NOI18N
        ButtonReports.setBorder(null);
        ButtonReports.setContentAreaFilled(false);
        ButtonReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonReportsMouseExited(evt);
            }
        });
        ButtonReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReportsActionPerformed(evt);
            }
        });
        JPAdminMenu.add(ButtonReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 170, 150));

        ButtonLogOut1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonLogOut1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonLogOut1.setForeground(new java.awt.Color(29, 41, 81));
        ButtonLogOut1.setText("Log Out");
        ButtonLogOut1.setBorder(null);
        ButtonLogOut1.setContentAreaFilled(false);
        ButtonLogOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonLogOut1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonLogOut1MouseExited(evt);
            }
        });
        ButtonLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOut1ActionPerformed(evt);
            }
        });
        JPAdminMenu.add(ButtonLogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 110, 40));

        ButtonQuery1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonQuery1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Query.png"))); // NOI18N
        ButtonQuery1.setBorder(null);
        ButtonQuery1.setContentAreaFilled(false);
        ButtonQuery1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonQuery1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonQuery1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonQuery1MouseExited(evt);
            }
        });
        ButtonQuery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQuery1ActionPerformed(evt);
            }
        });
        JPAdminMenu.add(ButtonQuery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, 170));

        ButtonConfiguration1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfiguration1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Configuration.png"))); // NOI18N
        ButtonConfiguration1.setBorder(null);
        ButtonConfiguration1.setContentAreaFilled(false);
        ButtonConfiguration1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonConfiguration1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonConfiguration1MouseExited(evt);
            }
        });
        ButtonConfiguration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfiguration1ActionPerformed(evt);
            }
        });
        JPAdminMenu.add(ButtonConfiguration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 170, 150));

        getContentPane().add(JPAdminMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        JPUserMenu.setBackground(new java.awt.Color(255, 255, 255));
        JPUserMenu.setForeground(new java.awt.Color(255, 255, 255));
        JPUserMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonQuery.setBackground(new java.awt.Color(255, 255, 255));
        ButtonQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Query.png"))); // NOI18N
        ButtonQuery.setBorder(null);
        ButtonQuery.setContentAreaFilled(false);
        ButtonQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonQueryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonQueryMouseExited(evt);
            }
        });
        ButtonQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQueryActionPerformed(evt);
            }
        });
        JPUserMenu.add(ButtonQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, 170));

        ButtonConfiguration.setBackground(new java.awt.Color(255, 255, 255));
        ButtonConfiguration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication16/Image/Configuration.png"))); // NOI18N
        ButtonConfiguration.setBorder(null);
        ButtonConfiguration.setContentAreaFilled(false);
        ButtonConfiguration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonConfigurationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonConfigurationMouseExited(evt);
            }
        });
        ButtonConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfigurationActionPerformed(evt);
            }
        });
        JPUserMenu.add(ButtonConfiguration, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 170, 150));

        ButtonLogOut.setBackground(new java.awt.Color(255, 255, 255));
        ButtonLogOut.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonLogOut.setForeground(new java.awt.Color(29, 41, 81));
        ButtonLogOut.setText("Log Out");
        ButtonLogOut.setBorder(null);
        ButtonLogOut.setContentAreaFilled(false);
        ButtonLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonLogOutMouseExited(evt);
            }
        });
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });
        JPUserMenu.add(ButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 110, 40));

        getContentPane().add(JPUserMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonQueryActionPerformed

    private void ButtonConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfigurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConfigurationActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
        JPWelcome.setVisible(true);
        JPUserMenu.setVisible(false);
        JPAdminMenu.setVisible(false);
        JPSignUp.setVisible(false);
    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void ButtonStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStatisticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonStatisticsActionPerformed

    private void ButtonReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonReportsActionPerformed

    private void ButtonLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOut1ActionPerformed
        JPWelcome.setVisible(true);
        JPUserMenu.setVisible(false);
        JPAdminMenu.setVisible(false);
        JPSignUp.setVisible(false);
    }//GEN-LAST:event_ButtonLogOut1ActionPerformed

    private void ButtonQuery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQuery1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonQuery1ActionPerformed

    private void ButtonConfiguration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfiguration1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConfiguration1ActionPerformed

    private void ButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignUpActionPerformed
        Animacion.Animacion.mover_derecha(290, 1100, 1, 1, JPWelcome);
        JPUserMenu.setVisible(false);
        JPAdminMenu.setVisible(false);
        JPSignUp.setVisible(true);
    }//GEN-LAST:event_ButtonSignUpActionPerformed

    private void ButtonRollbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRollbackActionPerformed
        JPWelcome.setVisible(true);
        JPUserMenu.setVisible(false);
        JPAdminMenu.setVisible(false);
        JPSignUp.setVisible(false);
    }//GEN-LAST:event_ButtonRollbackActionPerformed

    private void ButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnterActionPerformed
        Animacion.Animacion.mover_derecha(290, 1100, 1, 1, JPWelcome);
        JPUserMenu.setVisible(true);
        JPSignUp.setVisible(false);
        JPAdminMenu.setVisible(false);
    }//GEN-LAST:event_ButtonEnterActionPerformed

    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonCloseActionPerformed

    private void ButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinimizeActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_ButtonMinimizeActionPerformed

    private void ButtonRollbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRollbackMouseEntered
        ButtonRollback.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonRollbackMouseEntered

    private void ButtonRollbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRollbackMouseExited
        ButtonRollback.setBorder(null);
    }//GEN-LAST:event_ButtonRollbackMouseExited

    private void ButtonQuery1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonQuery1MouseEntered
        ButtonQuery1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonQuery1MouseEntered

    private void ButtonQuery1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonQuery1MouseExited
        ButtonQuery1.setBorder(null);
    }//GEN-LAST:event_ButtonQuery1MouseExited

    private void ButtonConfiguration1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfiguration1MouseEntered
        ButtonConfiguration1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonConfiguration1MouseEntered

    private void ButtonConfiguration1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfiguration1MouseExited
        ButtonConfiguration1.setBorder(null);
    }//GEN-LAST:event_ButtonConfiguration1MouseExited

    private void ButtonStatisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStatisticsMouseEntered
        ButtonStatistics.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonStatisticsMouseEntered

    private void ButtonStatisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStatisticsMouseExited
        ButtonStatistics.setBorder(null);
    }//GEN-LAST:event_ButtonStatisticsMouseExited

    private void ButtonReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonReportsMouseEntered
        ButtonReports.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonReportsMouseEntered

    private void ButtonReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonReportsMouseExited
        ButtonReports.setBorder(null);
    }//GEN-LAST:event_ButtonReportsMouseExited

    private void ButtonLogOut1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogOut1MouseEntered
        ButtonLogOut1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonLogOut1MouseEntered

    private void ButtonLogOut1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogOut1MouseExited
        ButtonLogOut1.setBorder(null);
    }//GEN-LAST:event_ButtonLogOut1MouseExited

    private void ButtonQueryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonQueryMouseEntered
        ButtonQuery.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonQueryMouseEntered

    private void ButtonQueryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonQueryMouseExited
        ButtonQuery.setBorder(null);
    }//GEN-LAST:event_ButtonQueryMouseExited

    private void ButtonConfigurationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfigurationMouseEntered
        ButtonConfiguration.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonConfigurationMouseEntered

    private void ButtonConfigurationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConfigurationMouseExited
        ButtonConfiguration.setBorder(null);
    }//GEN-LAST:event_ButtonConfigurationMouseExited

    private void ButtonLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogOutMouseEntered
        ButtonLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
        JPWelcome.setVisible(false);
    }//GEN-LAST:event_ButtonLogOutMouseEntered

    private void ButtonLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogOutMouseExited
        ButtonLogOut.setBorder(null);
    }//GEN-LAST:event_ButtonLogOutMouseExited

    private void ButtonCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCloseMouseEntered
        ButtonClose.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
    }//GEN-LAST:event_ButtonCloseMouseEntered

    private void ButtonCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCloseMouseExited
        ButtonClose.setBorder(null);
    }//GEN-LAST:event_ButtonCloseMouseExited

    private void ButtonMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeMouseEntered
        ButtonMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(29,41,81), 2));
    }//GEN-LAST:event_ButtonMinimizeMouseEntered

    private void ButtonMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeMouseExited
        ButtonMinimize.setBorder(null);
    }//GEN-LAST:event_ButtonMinimizeMouseExited

    private void ButtonSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSignUpMouseEntered
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        ButtonSignUp.setCursor(cursor);
    }//GEN-LAST:event_ButtonSignUpMouseEntered

    private void ButtonSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSignUpMouseExited
        Cursor cursor = new Cursor(Cursor.DEFAULT_CURSOR);
        ButtonSignUp.setCursor(cursor);
    }//GEN-LAST:event_ButtonSignUpMouseExited

    private void JPWelcomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPWelcomeMouseExited
        JPWelcome.setVisible(true);
        JPSignUp.setVisible(false);
        JPAdminMenu.setVisible(false);
        JPUserMenu.setVisible(false);
    }//GEN-LAST:event_JPWelcomeMouseExited

    private void JPWelcomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPWelcomeMouseEntered
        JPWelcome.setVisible(true);
        JPSignUp.setVisible(false);
        JPAdminMenu.setVisible(false);
        JPUserMenu.setVisible(false);
    }//GEN-LAST:event_JPWelcomeMouseEntered

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClose;
    private javax.swing.JButton ButtonConfiguration;
    private javax.swing.JButton ButtonConfiguration1;
    private javax.swing.JButton ButtonEnter;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JButton ButtonLogOut1;
    private javax.swing.JButton ButtonMinimize;
    private javax.swing.JButton ButtonQuery;
    private javax.swing.JButton ButtonQuery1;
    private javax.swing.JButton ButtonReports;
    private javax.swing.JButton ButtonRollback;
    private javax.swing.JButton ButtonSignUp;
    private javax.swing.JButton ButtonStatistics;
    private javax.swing.JLabel IconPassword;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel IconUsername;
    private javax.swing.JPanel JPAdminMenu;
    private javax.swing.JPanel JPLogin;
    private javax.swing.JPanel JPSignUp;
    private javax.swing.JPanel JPUserMenu;
    private javax.swing.JPanel JPWelcome;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelPassword1;
    private javax.swing.JLabel LabelSignUp;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel LabelUsername1;
    private javax.swing.JLabel LabelWelcome;
    private javax.swing.JSeparator LinePassword;
    private javax.swing.JSeparator LineUsername;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
