----En el esquema APP-----
CREATE TABLE gender(

    id      NUMBER(6),
    name    NUMBER(6)
);

ALTER TABLE gender
    ADD CONSTRAINT pk_gender PRIMARY KEY (id)
    USING INDEX
    TABLESPACE app_ind PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 20);

CREATE SEQUENCE seq_gender
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 10000000
NOCACHE
NOCYCLE;